{
    "client": {
        "address": "localhost",
        "ports": [
            6023,
            6029
        ]
    },
    "server": {
        "address": {
            "ip": "127.0.0.1",
            "port": 3099
        },
    }
}