default:
	@echo "\nUSAGE: make [option] \n"
	@echo "Options:"
	@echo "	build : build server"
	@echo "	buildw : build server on windows"

build:
	go build -o server.o ./cmd/server/main.go 
buildw:
	go build -o server.exe ./cmd/server/main.go 
